name: Build & Deploy Martin

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          docker build -t ghcr.io/${{ github.repository_owner }}/martin:$VERSION .
          docker tag ghcr.io/${{ github.repository_owner }}/martin:$VERSION ghcr.io/${{ github.repository_owner }}/martin:latest

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/martin:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/martin:latest

      - name: Clone infra repo
        run: |
          git clone https://ci-bot:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/infra.git

      - name: Update martin deployment image tag
        run: |
          cd infra/apps/services/martin
          sed -i "s|image: ghcr.io.*/martin.*|image: ghcr.io/${{ github.repository_owner }}/martin:$VERSION|" deployment.yaml

      - name: Commit manifest change
        run: |
          cd infra
          git config user.name "ci-bot"
          git config user.email "ci-bot@github.com"

          # (optionnel mais safe) s'assurer que le remote utilise bien le PAT
          git remote set-url origin https://ci-bot:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/infra.git

          git add .
          git commit -m "deploy: martin $VERSION" || echo "No changes to commit"
          git push origin main
        env:
          GIT_AUTHOR_NAME: ci-bot
          GIT_AUTHOR_EMAIL: ci-bot@github.com
          GIT_COMMITTER_NAME: ci-bot
          GIT_COMMITTER_EMAIL: ci-bot@github.com
